name: Docker Scan

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t test-image .

      - name: Show images
        run: docker images